macro(tutrc_ament_final)
  set(install_to_share "")
  if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/config")
    list(APPEND install_to_share "${CMAKE_CURRENT_SOURCE_DIR}/config")
  endif()
  if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/launch")
    list(APPEND install_to_share "${CMAKE_CURRENT_SOURCE_DIR}/launch")
  endif()
  if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/rviz")
    list(APPEND install_to_share "${CMAKE_CURRENT_SOURCE_DIR}/rviz")
  endif()

  ament_auto_package(INSTALL_TO_SHARE ${install_to_share})
endmacro()
